x-app-env: &app-env
  REDIS_URL: redis://redis:${REDIS_PORT:-6379}/0
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-mediavault_backend_development}
  DB_HOST: ${DB_HOST:-db}

services:
  app:
    container_name: mediavault-backend
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - ${DEFAULT_MOVIES_PATH:?please set its value in the .env file}:/media/library/movies:ro
      - ${DEFAULT_SHOWS_PATH:?please set its value in the .env file}:/media/library/shows:ro
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      <<: *app-env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    container_name: mediavault-backend-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mediavault_backend_development}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-mediavault_backend_development}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  sidekiq:
    container_name: mediavault-backend-sidekiq
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - ${DEFAULT_MOVIES_PATH:?please set its value in the .env file}:/media/library/movies:ro
      - ${DEFAULT_SHOWS_PATH:?please set its value in the .env file}:/media/library/shows:ro
    environment:
      <<: *app-env
    depends_on:
      - redis

  redis:
    container_name: mediavault-backend-redis
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  postgres_data:
