# This Dockerfile is designed for development.
# docker build -t mediavault-backend .

# For a containerized dev environment, see Dev Containers: https://guides.rubyonrails.org/getting_started_with_devcontainer.html

ARG RUBY_VERSION=4.0.6
FROM ruby:$RUBY_VERSION-slim AS base

# Rails app lives here
WORKDIR /app

# Install base packages
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    ffmpeg \
    git \
    curl

# Set production environment variables
ENV RAILS_ENV="development"

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Start server
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
